# Generated by Django 5.2.12 on 2026-03-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_tag_lecturematerial_eventtag'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_city_id_1cce9b_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
    ]
