# Generated by Django 5.2.12 on 2026-03-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avg_rating_user_birth_date_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_city_id_5da16b_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
